server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:

        - id: basic
          uri: http://localhost:8081
          predicates:
            - Path=/employeeManagements/**, 
        - id: basic_websocket
          uri: http://localhost:7081
          predicates:
            - Path=/rsocket/basics

        - id: sales
          uri: http://localhost:8082
          predicates:
            - Path=/orderManagements/**, 
        - id: sales_websocket
          uri: http://localhost:7082
          predicates:
            - Path=/rsocket/sales

        
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: basic
          uri: http://basic:8080
          predicates:
            - Path=/employeeManagements/**, 
        - id: sales
          uri: http://sales:8080
          predicates:
            - Path=/orderManagements/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
